name       : man-pages
version    : '6.04'
release    : 17
source     :
    - https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-6.04.tar.xz : c2c0b9329955df81af45ee80ebc84c47291f95df5157db1fab988199f9371af1
license    :
    - BSD-3-Clause
    - GPL-1.0-or-later
    - GPL-2.0-or-later
    - MIT
component  : system.utils
summary    : Linux manual pages
description: |
    A large collection of manual pages from the Linux Documentation Project (LDP).
mancompress: yes
rundeps    :
    - man-db
install    : |
    %make_install prefix=/usr

    # Remove conflicting files
    while read -r conflict; do
        rm -v $installdir/usr/share/man/$conflict
    done < $pkgfiles/man_conflicts
