name       : man-pages
version    : '4.10'
release    : 2
source     :
    - https://www.kernel.org/pub/linux/docs/man-pages/man-pages-4.10.tar.gz : 5995444d589a1ab83ae1220a4446ee09b3dadb6ce7037162ea75874ebcb2c040
    - https://www.kernel.org/pub/linux/docs/man-pages/man-pages-posix/man-pages-posix-2013-a.tar.xz : 19633a5c75ff7deab35b1d2c3d5b7748e7bd4ef4ab598b647bb7e7f60b90a808
license    :
    - GPL-1.0
    - GPL-2.0
component  : system.utils
summary    : Linux manual pages
rundeps    :
    - man-db
description: |
    Linux manual pages
setup      : |
    mkdir posix
    tar xf  $sources/man-pages-posix-2013-a.tar.xz --strip-components=1 -C posix
install    : |
    %make_install
    pushd posix
    %make_install

    # Remove conflicting files
    man_conflicts="man1/iconv.1"
    for conflict in $man_conflicts; do
        rm -v $installdir/usr/share/man/$conflict
    done

    # Make them usable.
    for i in 0p 1p 2 3 3p 4 5 6 7 8; do
        pushd "$installdir/usr/share/man/man$i"
        for i in *.$i ; do
            gzip --verbose $i;
        done
        popd
    done

