name       : man-pages
version    : '5.06'
release    : 13
source     :
    - https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-5.06.tar.xz : 70b8a902a9daa0a596188c1925373199dbad590eb06d7c0e505c4b33e8bbfe50
license    :
    - BSD-3-Clause
    - GPL-1.0-or-later
    - GPL-2.0-or-later
    - MIT
component  : system.utils
summary    : Linux manual pages
description: |
    A large collection of manual pages from the Linux Documentation Project (LDP).
rundeps    :
    - man-db
install    : |
    %make_install

    # Remove conflicting files
    man_conflicts="man1/iconv.1"
    for conflict in $man_conflicts; do
        rm -v $installdir/usr/share/man/$conflict
    done

    # Make them usable.
    for i in 1 2 3 4 5 6 7 8; do
        pushd "$installdir/usr/share/man/man$i"
        for i in *.$i ; do
            gzip --verbose $i;
        done
        popd
    done
