name       : man-pages
version    : '5.04'
release    : 11
source     :
    - https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-5.04.tar.xz : 7d04fb1094bb7bd218cf7a9e4493871903576054e7d1e89d8f06cb4584e6a4af
license    :
    - BSD-3-Clause
    - GPL-1.0-or-later
    - GPL-2.0-or-later
    - MIT
component  : system.utils
summary    : Linux manual pages
description: |
    A large collection of manual pages from the Linux Documentation Project (LDP).
rundeps    :
    - man-db
install    : |
    %make_install

    # Remove conflicting files
    man_conflicts="man1/iconv.1"
    for conflict in $man_conflicts; do
        rm -v $installdir/usr/share/man/$conflict
    done

    # Make them usable.
    for i in 1 2 3 4 5 6 7 8; do
        pushd "$installdir/usr/share/man/man$i"
        for i in *.$i ; do
            gzip --verbose $i;
        done
        popd
    done
